feat(15 matrices): Using <exclude> option

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -29,9 +29,9 @@ jobs:
         with:
           node-version: ${{matrix.node}}
 
-      - name: Fail If Experimental
-        if: ${{matrix.tag == 'experimental'}}
-        run: exit 1
+      # - name: Fail If Experimental
+      #   if: ${{matrix.tag == 'experimental'}}
+      #   run: exit 1
 
       - name: Perform Some Tests
         run: |
@@ -58,9 +58,13 @@ jobs:
           - color: red
             shape: triangle
           - opacity: 50
+          - color: green
+            shape: circle
+            size: medium
 
         exclude:
-          - opacity: 75
+          - color: green
+            shape: circle
 
     steps:
       - name: Dummy Step
